name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install node modules
      run: npm install
    - name: Execute static security tests
      run: npm audit
    - name: Install Playwright system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libwoff1 \
          libvpx7 \
          libevent-2.1-7 \
          libopus0 \
          gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-libav \
          libharfbuzz-icu0 \
          libsecret-1-0 \
          libhyphen0 \
          libmanette-0.2-0 \
          flite \
          libgles2-mesa \
          libx264-160  
    - name: Run servers in background
      run: |
        npm start &           
        node server/server.js &  
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Execute integration tests
      run: npm test
