name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install node modules
      run: npm install
    - name: Execute static security tests
      run: npm audit  
    - name: Run servers in background
      run: |
        npm start &           
        node server/server.js &  
    - name: Install Playwright browsers
      run: npm install playwright
    - name: Execute integration tests
      run: npm test
